[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# SPA routing - redirect specific dashboard routes but NOT assets
[[redirects]]
  from = "/dashboard/prompts/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/sources"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/sources/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/competitors"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/competitors/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/tags"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/tags/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/people"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/people/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/workspace"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/workspace/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/company"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/company/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/billing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/billing/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/subscription"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/subscription/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/settings"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/settings/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/best-practices"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/best-practices/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/recommendations"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/recommendations/*"
  to = "/index.html"
  status = 200

# Other page routes
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/agency"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"