[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Serve static files directly (assets, JS, CSS)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat.jpeg"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200

# SPA routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"